require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LpusController do

  # This should return the minimal set of attributes required to create a valid
  # Lpu. As you add validations to Lpu, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "provedor" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LpusController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all lpus as @lpus" do
      lpu = Lpu.create! valid_attributes
      get :index, {}, valid_session
      assigns(:lpus).should eq([lpu])
    end
  end

  describe "GET show" do
    it "assigns the requested lpu as @lpu" do
      lpu = Lpu.create! valid_attributes
      get :show, {:id => lpu.to_param}, valid_session
      assigns(:lpu).should eq(lpu)
    end
  end

  describe "GET new" do
    it "assigns a new lpu as @lpu" do
      get :new, {}, valid_session
      assigns(:lpu).should be_a_new(Lpu)
    end
  end

  describe "GET edit" do
    it "assigns the requested lpu as @lpu" do
      lpu = Lpu.create! valid_attributes
      get :edit, {:id => lpu.to_param}, valid_session
      assigns(:lpu).should eq(lpu)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Lpu" do
        expect {
          post :create, {:lpu => valid_attributes}, valid_session
        }.to change(Lpu, :count).by(1)
      end

      it "assigns a newly created lpu as @lpu" do
        post :create, {:lpu => valid_attributes}, valid_session
        assigns(:lpu).should be_a(Lpu)
        assigns(:lpu).should be_persisted
      end

      it "redirects to the created lpu" do
        post :create, {:lpu => valid_attributes}, valid_session
        response.should redirect_to(Lpu.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved lpu as @lpu" do
        # Trigger the behavior that occurs when invalid params are submitted
        Lpu.any_instance.stub(:save).and_return(false)
        post :create, {:lpu => { "provedor" => "invalid value" }}, valid_session
        assigns(:lpu).should be_a_new(Lpu)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Lpu.any_instance.stub(:save).and_return(false)
        post :create, {:lpu => { "provedor" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested lpu" do
        lpu = Lpu.create! valid_attributes
        # Assuming there are no other lpus in the database, this
        # specifies that the Lpu created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Lpu.any_instance.should_receive(:update_attributes).with({ "provedor" => "MyString" })
        put :update, {:id => lpu.to_param, :lpu => { "provedor" => "MyString" }}, valid_session
      end

      it "assigns the requested lpu as @lpu" do
        lpu = Lpu.create! valid_attributes
        put :update, {:id => lpu.to_param, :lpu => valid_attributes}, valid_session
        assigns(:lpu).should eq(lpu)
      end

      it "redirects to the lpu" do
        lpu = Lpu.create! valid_attributes
        put :update, {:id => lpu.to_param, :lpu => valid_attributes}, valid_session
        response.should redirect_to(lpu)
      end
    end

    describe "with invalid params" do
      it "assigns the lpu as @lpu" do
        lpu = Lpu.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Lpu.any_instance.stub(:save).and_return(false)
        put :update, {:id => lpu.to_param, :lpu => { "provedor" => "invalid value" }}, valid_session
        assigns(:lpu).should eq(lpu)
      end

      it "re-renders the 'edit' template" do
        lpu = Lpu.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Lpu.any_instance.stub(:save).and_return(false)
        put :update, {:id => lpu.to_param, :lpu => { "provedor" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested lpu" do
      lpu = Lpu.create! valid_attributes
      expect {
        delete :destroy, {:id => lpu.to_param}, valid_session
      }.to change(Lpu, :count).by(-1)
    end

    it "redirects to the lpus list" do
      lpu = Lpu.create! valid_attributes
      delete :destroy, {:id => lpu.to_param}, valid_session
      response.should redirect_to(lpus_url)
    end
  end

end
